### ISSUE TITLE
为什么我写爬下来的图片全部挂掉了- -？

### ISSUE THREAD

**Issue by CommanderXL** [rockdai/haixiu#3]
RT。

状态码是403 Forbidden.

**Comment by alsotang** [comment]
用 https 就不会挂了。否则会被防盗链机制返回 403.

2015-05-17 21:38 GMT+08:00 XRene <notifications@github.com>:

**Comment by CommanderXL** [comment]
嗯。了解。

另外就是在crawler文件夹里面superagent会请求一个https://database.duoshuo.com/api/threads/listPosts.json?thread_key=haixiuzu&page=1&limit=100 
这个地址。这个地址应该是存放着JSON格式的网站里面的所有的记录信息。

那么这个记录信息应该是自己写的程序爬下来的吧？
